### ISSUE TITLE
Please dont abandon the app now official F1TV app is live

### ISSUE THREAD

**Issue by Invictaz** [leonardoxh/race-control-tv#102]
The official F1TV app for AndroidTV is out, but

1. It is not available on even my brand new Philips Android TV via the Play Store
2. If I sideload it via APK it is much slower than your app. 

So please don't abandon your app now the official one is there.

**Comment by leonardoxh** [comment]
I have the official app here installed on my TV as well, but it indeed looks very slow.

I won't deprecated this app immediately for sure. Thanks for the support
