### ISSUE TITLE
App only shows empty 2022 season

### ISSUE THREAD

**Issue by cgburgess** [leonardoxh/race-control-tv#107]
Hi I just sideloaded the app on my 4K fire stick. I open the app and login and I only see current season is 2022 and there are no other options or buttons besides settings. The 2022 season has no cards or things to press. 

![image](https://user-images.githubusercontent.com/9002722/147886532-3765483f-5535-4bfa-a074-7a64d58b88d2.jpg)

**Comment by leonardoxh** [comment]
Interesting, will patch this asap.

**Comment by leonardoxh** [comment]
I patched it, just waiting for play store to validate if my change really works, but it should be out late today. Thanks once again for the report.

**Comment by leonardoxh** [comment]
It is available now.

**Comment by cgburgess** [comment]
Works brilliantly thank you!

**Comment by tomeeee** [comment]
Hi, I am having same issue on firestick 4k. Sideloaded version 2.6.0, tried reinstal, clear cash and data. Still having the same issue. Only season  2022 is showed like on picture above.
