### ISSUE TITLE
App not showing after install

### ISSUE THREAD

**Issue by dannybUK** [leonardoxh/race-control-tv#112]
I've installed the app but it doesn't appear in my app drawer. When it installs if I press open straight away it doesn't load.
If I go into settings and apps I can see it there and am able to uninstall.
Running Android 10, MIUI 12.0.4

**Comment by leonardoxh** [comment]
Hi sir, 

How did you install the app ? Via PlayStore or did you side load it ?

**Comment by dannybUK** [comment]
Hi,
I side loaded it. I thought it was removed from the play store? I can only see the Android TV version there.

**Comment by leonardoxh** [comment]
Yeah, some people had the app already installed, nvm.

I don't know for sure what is going on, but it seems more like a problem with TV launcher.

Just to be sure it is a TV right?

**Comment by dannybUK** [comment]
No it isn't apologies. I was hoping to get it running on my phone and tablet. I didn't realise it was only for TVs. I will try it on my firestick though.
