### ISSUE TITLE
Blocked by bot detection

### ISSUE THREAD

**Issue by dseven** [leonardoxh/race-control-tv#113]
Apparently F1TV has implemened some attempt at bot detection. It seems to be affecting this app too - at least I can't get logged in on two devices that were working for the last race. Some discussion at 

https://www.reddit.com/r/F1TV/comments/tya3qu/f1tv_has_ruined_racecontrol_andf1viewer/

https://github.com/robvdpol/RaceControl/issues/414

https://github.com/SoMuchForSubtlety/f1viewer/issues/231

**Comment by mhil70** [comment]
Hi @leonardoxh , 
Do you expect to get a fix or workaround to solve this login issue?
Would be great!

**Comment by leonardoxh** [comment]
Hi, I am expecting a fix to be out today :D

**Comment by mhil70** [comment]
> Hi, I am expecting a fix to be out today :D

Wow, that would be great and make my weekend...👍

**Comment by leonardoxh** [comment]
Here is the PR:

https://github.com/leonardoxh/race-control-tv/pull/114

I released right now to open testing on play store (for the stores that are not banned).

Most likely later today I will have the apk ready if everything is alright

**Comment by leonardoxh** [comment]
Everything tested and apk is available here: https://github.com/leonardoxh/race-control-tv/releases/tag/v2.6.1

**Comment by dseven** [comment]
Looks good to me! Thanks very much for the quick turnaround!
