### ISSUE TITLE
Not able to watch Live and recent Sessions, DRM issue

### ISSUE THREAD

**Issue by LoVega1337** [leonardoxh/race-control-tv#119]
So I tried watching the Australian FP2 replay and the player just stays blank and doesn't retrieve any video. 
This might be the first indication that F1TV is cracking down on 3rd party apps that don't support Widevine DRM.

This might be an issue with the ExoPlayer not supporting Widevine but I'm not sure yet. See for reference: https://github.com/robvdpol/RaceControl/issues/414#issuecomment-1092454241

Edit: ExoPlayer does in fact support DRM, just isn't configured in this app yet. This might need some work, otherwise the app can't play live and recent sessions.

**Comment by meisterj** [comment]
Same issue here, Philips Android TV, cant watch recent race/training. highlights work, so i think its an Language issue? highlights are only in english

**Comment by LoVega1337** [comment]
@meisterj Not a language issue, this is a DRM issue. Everything except the International feeds of the main events are exclusively in English.

**Comment by juangzz** [comment]
Same issue here :’(

**Comment by nelis68** [comment]
Same problem here , it seems a time issue. After a couple of hours it works .

**Comment by leonardoxh** [comment]
Yep this has to do with the DRM part.

I have some ideas to play around with, but it is going to take some time.

**Comment by Woziak** [comment]
With the 2.6.1 apk  I am able to login but it does not start the app after login.
I am on a DuneHD Android TV player.

**Comment by gazdajezda** [comment]
Same here. Newest apk on Phillips POS9002 Android TV. Old races works, also now i can watch todays qually, but at the time of live event and even for some hour, player was blank. Seems they let open non-drm content available later.

**Comment by LoVega1337** [comment]
@leonardoxh I read through a couple of documentations of ExoPlayer and the implementation of DRM might be quite simple, although the current implementation of the ExoPlayer itself looks kinda complicated so I need a bit of help here.

The license URL from F1TV is this URL (with edited CHANNEL_ID and CONTENT_ID var): 
`https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_HLS/ALL/CONTENT/LA/widevine?channelId=$CHANNEL_ID&contentId=$CONTENT_ID`

My quick and dirty Implementation of it ([according to the ExoPlayer doc](https://exoplayer.dev/media-items.html#protected-content)) in the ChannelPlaybackFragment.kt:

```java
private static @Nullable UUID getDrmUuid(String drmScheme) {
        switch (toLowerInvariant(drmScheme)) {
            case "widevine":
                return C.WIDEVINE_UUID;
            case "playready":
                return C.PLAYREADY_UUID;
            case "clearkey":
                return C.CLEARKEY_UUID;
            default:
                try {
                return UUID.fromString(drmScheme);
              } catch (RuntimeException e) {
                return null;
              }
         }
    }

    private val player: ExoPlayer by lazy {
        val player = ExoPlayer.Builder(requireContext())
            .setTrackSelector(trackSelector)
            .setDrmConfiguration(
                new ExoPlayer.DrmConfiguration.Builder(C.WIDEVINE_UUID)
                    .setLicenseUri("https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_HLS/ALL/CONTENT/LA/widevine?channelId=$CHANNEL_ID&contentId=$CONTENT_ID")
                    .setMultiSession(true)
                    .setLicenseRequestHeaders(httpDataSourceFactory) // Might need to be changed back to "httpRequestHeaders"
                    .build())
            .build()
        player.playWhenReady = true
        player.addAnalyticsListener(EventLogger(trackSelector))
        player
    }

**Comment by nilsnilsnils** [comment]
> Same problem here , it seems a time issue. After a couple of hours it works .

Same Herr

**Comment by leonardoxh** [comment]
@LoVega1337 looks awesome to start with at least. Thanks

**Comment by leonardoxh** [comment]
I released today this one:

https://github.com/leonardoxh/race-control-tv/releases/tag/v2.6.2

Which will fix the DRM issues, I only tested with the F3 sessions but seems to work fine. I will keep this thread open until I know for sure this fixed everything.

**Comment by LoVega1337** [comment]
Works beautifully for me, awesome!

Although:
- The International and F1 Live cards are in all-caps, so they're named "INTERNATIONAL" and "F1 LIVE"
- The International channel card is at the bottom and end of all channels, behind all drivers

- The one note in the changelog where it says the International channel doesn't show up for 2021 and previous seasons isn't true for me, it's there for me but again at the bottom and end of all cards

**Comment by bashopman** [comment]
Works like a charm! Thanks!

**Comment by meisterj** [comment]
Tahnk You!!! Works for me now :-)

**Comment by ragnos** [comment]
While it did work yesterday, today during the Porsche Cup Practice the stream doesn't start for me. Replays work. The player takes some seconds with the spinning wheel animation, then crashes and starts again. Can't even enter the language settings because it all happens so quick.

![Screenshot 2022-04-23 09-35-22](https://user-images.githubusercontent.com/5920732/164885132-0dd20677-8601-434d-b323-f3a39516085a.png)

FireTV 4k, App Version 2.6.2. Deleted cache, then all data, then removed the app and sideloaded again. No change in behaviour.

**Comment by leonardoxh** [comment]
I've noticed that I might have messed up the links a bit 😅 will test new stuff today

**Comment by Vlame04** [comment]
I have the same problem. With F1, F2 and F3 I can watch the replays but I can't watch the live sessions. From PSC I can't watch anything

**Comment by ArneAbbink** [comment]
Exactly the same issue over here. No live content, only replays.

**Comment by nilsnilsnils** [comment]
Same here cant watch f1 Sprint live. Yesterday everything was Fine.

**Comment by Zorrobus** [comment]
Same here, no live stream, crash season 2019. Sony Android TV

**Comment by Dlopezv92** [comment]
Same problem here. Worked in the yesterday qualy but today in the Imola Sprint doesn’t work. The icon Load is always in the screen and doesn’t load anything

**Comment by koningcool** [comment]
For me also the same problem last race, wish you luck with fixing it @leonardoxh

**Comment by ragnos** [comment]
The issue persists with the currently starting fp1 session.

**Comment by rulasmarmol** [comment]
Same here, live stream not working, only replays.

**Comment by Coedy** [comment]
Same here. 
I get a spinning loading animation, and restart of the stream (with the same spinning loading animation). 
Good luck @leonardoxh!

**Comment by pietjelombok** [comment]
Live stream is not starting

**Comment by Dominion99NL** [comment]
I cannot get it to work, I have removed the app on my Sony Android TV and installed it again, i do get a login page from the F1 website, enter my credentials but after successfull login, i'm taking to the dashboard from the F1 website, do i miss a button somewhere to return to the F1 App because i'm never getting back to the F1 app, when i close the app and restart the process is repeating itself.

**Comment by LoVega1337** [comment]
@leonardoxh
So I did a little bit of investigation and it seems like it kind of fetches the wrong `sessionId` or `contentId`. I started the last replay from the Miami GP through the F1TV site and it fetches the following .mpd URL:
`https://ott-video-cf.formula1.com/6180c994cb835402/out/v1/95a456635d9f4a22bf3423fda15932ff/index.mpd?[...]`
I tried starting the same replay on the app in debug mode and it tries to fetch the URL:
`https://ott-video-cf.formula1.com/6180c994cb835402/out/v1/02dd87aa3baf42ba934707e36f52cb9a/index.mpd?[...]`
This throws me an 403 error in the app and when copying it into the browser, the other URL from the F1TV site works fine and starts downloading the index.mpd.

The `ChannelPlaybackFragment.kt` fetches the complete URL, although I'm not sure where it gets the different IDs from.

**Comment by Shamrayev365** [comment]
Is this project still alive?

**Comment by WouterVork** [comment]
Wondering the same thing. The quality of the stream is (or was) so much better than the official app

**Comment by jonathanflack** [comment]
I am seeing the exact same behavior as @LoVega1337 today when trying to load the Monaco quali replay for F1.  It's fetching the wrong URL and failing.  Screen is exactly as @ragnos posted earlier.

Worked fine for P3 highlights.

**Comment by nilsnilsnils** [comment]
Idee for a Workaround with a self created apk.

Can anyone create a fork where the Login webseite appears on every start and the name and password will be auto filled from Text file and the Login finishes auto.? 



Editing the text file and creating the apk myself is not the problem.

**Comment by leonardoxh** [comment]
The project is still alive, but I do not have a way to fix the DRM issue yet, unfortunately

**Comment by jmarttila** [comment]
I have been able to stream all of the recent races live using my own patches. I needed to change streaming to HLS, and attach `User-Agent`, `ascendontoken` and `entitlementtoken` to the `DrmConfiguration` in `MediaSourceItemFactory`

Examples:
* Use DASH
```
-        private const val PLAY_URL = "https://f1tv.formula1.com/1.0/R/ENG/BIG_SCREEN_%s/ALL/CONTENT/PLAY?contentId=%s"
-        const val DRM_URL = "https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_HLS/ALL/CONTENT/LA/widevine?contentId=%s&channelId=%s"
+        private const val PLAY_URL = "https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_%s/ALL/CONTENT/PLAY?contentId=%s"
+        const val DRM_URL = "https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_DASH/ALL/CONTENT/LA/widevine?contentId=%s"
```

* Headers
```
                MediaItem.DrmConfiguration.Builder(C.WIDEVINE_UUID)
                    .setLicenseRequestHeaders(
                        mutableMapOf(
                            "User-Agent" to BuildConfig.DEFAULT_USER_AGENT,
                            "ascendontoken" to "<token>",
                            "entitlementtoken" to <token>
                        )
                    )
                    .setLicenseUri(F1Client.DRM_URL.format(viewing.contentId))
                    .setMultiSession(true)
                    .build()

```

**Comment by nilsnilsnils** [comment]
> I have been able to stream all of the recent races live using my own patches. I needed to change streaming to HLS, and attach `User-Agent`, `ascendontoken` and `entitlementtoken` to the `DrmConfiguration` in `MediaSourceItemFactory`
> 
> 
> 
> Examples:
> 
> * Use DASH
> 
> ```
> 
> -        private const val PLAY_URL = "https://f1tv.formula1.com/1.0/R/ENG/BIG_SCREEN_%s/ALL/CONTENT/PLAY?contentId=%s"
> 
> -        const val DRM_URL = "https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_HLS/ALL/CONTENT/LA/widevine?contentId=%s&channelId=%s"
> 
> +        private const val PLAY_URL = "https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_%s/ALL/CONTENT/PLAY?contentId=%s"
> 
> +        const val DRM_URL = "https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_DASH/ALL/CONTENT/LA/widevine?contentId=%s"
> 
> ```
> 
> 
> 
> * Headers
> 
> ```
> 
>                 MediaItem.DrmConfiguration.Builder(C.WIDEVINE_UUID)
> 
>                     .setLicenseRequestHeaders(
> 
>                         mutableMapOf(
> 
>                             "User-Agent" to BuildConfig.DEFAULT_USER_AGENT,
> 
>                             "ascendontoken" to "<token>",
> 
>                             "entitlementtoken" to "<token>"
> 
>                         )
> 
>                     )
> 
>                     .setLicenseUri(F1Client.DRM_URL.format(viewing.contentId))
> 
>                     .setMultiSession(true)
> 
>                     .build()
> 
> 
> 
> ```

Can you create an APK that we can test it :)?

**Comment by jmarttila** [comment]
I just hardcoded the tokens into the APK I deployed to my device, it does not provide the necessary login/token aquiring flows. If you want to test this out, you'll want to build the app yourself with the necessary tokens.

In addition, only live streams work so it's not really a full solution. I haven't had time to make a general solution.

**Comment by leonardoxh** [comment]
This is a port of the solution above:

https://github.com/leonardoxh/race-control-tv/pull/136

Will try it out this weekend

**Comment by leonardoxh** [comment]
I have this test APK: https://drive.google.com/file/d/1oDTbyt-scbkqqM-Xt3ChBa8WLmg-tFz5/view?usp=sharing

The current content works and I see the DRM Loggins going, however I need to test this more Friday with the live content.

**Comment by gazdajezda** [comment]
Np. I will test it too :)

**Comment by jmarttila** [comment]
The test PR branch did not work directly with live streaming. However, I could get it to work when I applied the changes I did exactly:

```
diff --git a/app/src/main/java/fr/groggy/racecontrol/tv/f1/F1Client.kt b/app/src/main/java/fr/groggy/racecontrol/tv/f1/F1Client.kt
index c397911..3d1dd18 100644
--- a/app/src/main/java/fr/groggy/racecontrol/tv/f1/F1Client.kt
+++ b/app/src/main/java/fr/groggy/racecontrol/tv/f1/F1Client.kt
@@ -23,8 +23,8 @@ class F1Client @Inject constructor(
     companion object {
         const val API_KEY = "fCUCjWrKPu9ylJwRAv8BpGLEgiAuThx7"
 
-        private const val PLAY_URL = "https://f1tv.formula1.com/1.0/R/ENG/BIG_SCREEN_%s/ALL/CONTENT/PLAY?contentId=%s"
-        const val DRM_URL = "https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_HLS/ALL/CONTENT/LA/widevine?contentId=%s&channelId=%s"
+        private const val PLAY_URL = "https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_%s/ALL/CONTENT/PLAY?contentId=%s"
+        const val DRM_URL = "https://f1tv.formula1.com/2.0/R/ENG/BIG_SCREEN_DASH/ALL/CONTENT/LA/widevine?contentId=%s"
     }
 
     private val viewingResponseJsonAdapter = moshi.adapter(F1TvViewingResponse::class.java)
diff --git a/app/src/main/java/fr/groggy/racecontrol/tv/ui/channel/playback/ChannelPlaybackActivity.kt b/app/src/main/java/fr/groggy/racecontrol/tv/ui/channel/playback/ChannelPlaybackActivity.kt
index aae0f2d..e16d92f 100644
--- a/app/src/main/java/fr/groggy/racecontrol/tv/ui/channel/playback/ChannelPlaybackActivity.kt
+++ b/app/src/main/java/fr/groggy/racecontrol/tv/ui/channel/playback/ChannelPlaybackActivity.kt
@@ -43,7 +43,7 @@ class ChannelPlaybackActivity : FragmentActivity(R.layout.activity_channel_playb
         super.onCreate(savedInstanceState)
 
         lifecycleScope.launchWhenCreated {
-            attachViewingIfNeeded(Settings.StreamType.DASH_HLS)
+            attachViewingIfNeeded(Settings.StreamType.DASH)
         }
     }
 
@@ -113,13 +113,13 @@ class ChannelPlaybackActivity : FragmentActivity(R.layout.activity_channel_playb
                 remove(fragment)
                 runOnCommit {
                     lifecycleScope.launch {
-                        attachViewingIfNeeded(Settings.StreamType.HLS)
+                        attachViewingIfNeeded(Settings.StreamType.DASH)
                     }
                 }
             }
         } else {
             lifecycleScope.launch {
-                attachViewingIfNeeded(Settings.StreamType.HLS)
+                attachViewingIfNeeded(Settings.StreamType.DASH)
             }
         }
     }
```

**Comment by leonardoxh** [comment]
It is released:

https://github.com/leonardoxh/race-control-tv/releases/tag/2.7.0

I will keep this issue open still for this weekend and if everything works we can finally close this monster.

**Comment by nilsnilsnils** [comment]
Thanks for your work :)

**Comment by gazdajezda** [comment]
Great! Can't wait to watch again on TV :)

**Comment by leonardoxh** [comment]
Could be @nilsnilsnils

**Comment by WouterVork** [comment]
Thank you so much everybody! The F2 session right now works perfectly on my phone! (I don't have access to my TV right now)

**Comment by ptrdom** [comment]
I have just checked the live F2 session on TV, works well, many thanks! Maintenance of this app is very much appreciated!

**Comment by jonathanflack** [comment]
Works well for FP1 replay at 1080/50, playback, rewind, fast fwd, etc. are all dramatically better behaved.  Awesoem Silverstone upgrade package!

**Comment by nilsnilsnils** [comment]
FP2 live works perfecly :)

**Comment by jonathanflack** [comment]
Confirming ALL channels for FP2 Live were fully functional.  Data, Onboards, etc., working perfectly.  Now all we need is these feeds upgraded to 4k by F1.. for an organization that talks a lot about technology they sure are stuck in the 90's when it comes to their broadcast.

Again, great work by everyone who contributed here.  Could not have come at a better time given it's Silverstone.  Cheers!

**Comment by leonardoxh** [comment]
With no regrets I am closing this issue

**Comment by MarcoDS** [comment]
Amazing work, thank you for not giving up on this project, my wife and I love it !
