### ISSUE TITLE
Fire TV support

### ISSUE THREAD

**Issue by antoinel12** [leonardoxh/race-control-tv#12]
Amazon's Fire TV (as it is based on Android) support would be really nice if possible.

Maybe this could help:
https://developer.amazon.com/fr/docs/fire-tv/differences-from-android-tv-development.html

Thanks!

**Comment by leonardoxh** [comment]
I believe this should be pretty straight forward as we do not use google play services and so on, I will take a look for sure

**Comment by leonardoxh** [comment]
However I see F1 has the app on amazon store...

Does it work with Fire tvs ? 

https://www.amazon.co.uk/Formula-One-Digital-Media-Limited/dp/B077VPVD47

**Comment by antoinel12** [comment]
The version on Amazon store is only working for fireOS tablets (it's the same as Android phones and tablets).

I've tried to sideload the apk from the original repo you have forked from but it won't let me install it. Maybe it's apk's metadata or SDK version requirement ?

Currently my FireTV Stick 4k is running on Fire OS 6 (based on Android 7.1). The new version. The new version of the Stick (october 2020) is running Fire OS 7 (based on Android 9).

**Comment by leonardoxh** [comment]
I believe it has to do with the min ask version, right now it is set to Android 8

**Comment by leonardoxh** [comment]
@antoinel12 I reduced the minSdkVersion to 21 right now, seems like everything is working.

Could you side load the apk on your fire tv to test?

**Comment by antoinel12** [comment]
It crash after login:
AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Clock;

Looklike java.time is only available from Android Oreo (API 26).

Amazon is supposed to release the new UI for my model of Fire TV stick later this month. If I'm lucky, they will upgrade it to Fire OS 7 which is based on Android 9.

**Comment by leonardoxh** [comment]
Yeah, in this case we could use a support library. I will patch it

**Comment by leonardoxh** [comment]
Hi @antoinel12 

I have made some changes to the code to use a support library instead of java time clock.

Can you try to side load the latest `master` branch ? and let me know if it works ? I think we could publish it to amazon store

**Comment by antoinel12** [comment]
It's working!

Good job!

**Comment by leonardoxh** [comment]
Fantastic. Btw, I will release this week support to the new apis. 

Closing this for now

**Comment by andrew-dixon** [comment]
@leonardoxh I've just installed v2.0.3 on my Fire TV 4K stick and it will not play the videos. You click on a video to watch and it loads the player and then immediately closes it again, putting you back to the list.

**Comment by leonardoxh** [comment]
I noticed this a sometimes on my emulator, if you try again does it work?

Also is it exclusively to the live sessions happening now ? I see on redit many people heaving issues with F1 services, can you confirm if you are able to watch on the website?

**Comment by andrew-dixon** [comment]
@leonardoxh It seems to be all the videos, not jus the live session and I'm able to watch ok on my iPad.

**Comment by leonardoxh** [comment]
I added this to the issue list.

https://github.com/leonardoxh/race-control-tv/issues/48

However I am convicted that this is somehow an API issue.
