### ISSUE TITLE
Any choice but Accept All for cookies impossible to set on sideloaded app with Bravia TV

### ISSUE THREAD

**Issue by jonathanflack** [leonardoxh/race-control-tv#122]
v2.6.1
When logging in the first time after sideloading the apk on Bravia TV user is presented with a cookie acceptance dialogue, however the dialogue is impossible to navigate on screen (zoom level on browser), and it does not allow for the selection of "Deny All" selection.  The only way to proceed past this screen is to Accept all when the dialogue first loads.

**Comment by leonardoxh** [comment]
Closing this issue.

I have no control over the web browser page.
