### ISSUE TITLE
Main Broadcast 

### ISSUE THREAD

**Issue by zander330i** [leonardoxh/race-control-tv#123]
Main Broadcast does not play when live.

**Comment by Kaspersen872** [comment]
Same here, Replays and Highlights works but not Live

**Comment by nelis68** [comment]
Same here , no  live broadcast ..

**Comment by XVBinh** [comment]
Same here

**Comment by robinclement1993** [comment]
I'm having the same issue. Live broadcasting won't stream. Doesn't matter which channel I choose. Replays do work.

**Comment by noelvissers** [comment]
Could be the same issue as mentioned in https://github.com/leonardoxh/race-control-tv/issues/119

**Comment by leonardoxh** [comment]
Closing this in favour of #119
