### ISSUE TITLE
Can't login even though username and password are correct 

### ISSUE THREAD

**Issue by WouterVork** [leonardoxh/race-control-tv#124]
I have had this app for some months and it is very good! Thank you!
Today I opened it and for some reason I had to login again.
I entered my email address and password, but it said they were incorrect. I tried multiple things, such as logging in and out in my browser, changing my password and entering my display name as my username, but it still doesn't work. 
I'm kind of at a loss right now on what to do as my TV doesn't support the official app and the stream is very choppy when casting from my phone.

**Comment by noelvissers** [comment]
You need to update the app. The app is removed from the play store as requested by formula 1, so you need to manually update it as described on this page.

**Comment by WouterVork** [comment]
> You need to update the app. The app is removed from the play store as requested by formula 1, so you need to manually update it as described on this page.

How do I do that on my TV? Sorry, I am a noob regarding this

**Comment by WouterVork** [comment]
> > You need to update the app. The app is removed from the play store as requested by formula 1, so you need to manually update it as described on this page.
> 
> How do I do that on my TV? Sorry, I am a noob regarding this

I used the Send Files to TV app to send the 2.6.1 apk to my TV and it works perfectly now! Thanks!
