### ISSUE TITLE
Not able to download app through play store

### ISSUE THREAD

**Issue by kleinMaggus** [leonardoxh/race-control-tv#129]
I've recently had issues to login in and wanted to reinstall the app. But unfortunately the app can not be found in the play store anymore. It's not available for my Sony KD-65XE8505 with Version 9 (propably android version).

Did you update the app for only newer android versions? 
If you require further information just let my know.

**Comment by Vlame04** [comment]
It is right that the app cannot be downloaded using the playstore anymore. The old login doesn't work anymore so you need to install the newest version from Github. Then the login will work again

**Comment by kleinMaggus** [comment]
Thanks. That worked.
