### ISSUE TITLE
No apk available for download?

### ISSUE THREAD

**Issue by rafael2k** [leonardoxh/race-control-tv#17]
Hi,
Do you provide the apk? I'm still using race-control-tv from other forks, but yours seems to be the most advanced.

**Comment by leonardoxh** [comment]
Hi, I published the app on Google Playstore (links on Readme file), do you have a special need for the apk itself ?

**Comment by rafael2k** [comment]
Thanks Leonardo. I'm trying to install it on my NVIDIA Shield, but the race-control-tv does not appear in the store. I'm thinking in side-loading it, as I already did with other apks.

**Comment by leonardoxh** [comment]
What is the android version of your device / the country you are located?

I released an update yesterday to the store lowering the api level from 26 to 21 to support fire tvs, it might appear now, but it might also be that I did not release the app in your country, so then I have to fix that

**Comment by leonardoxh** [comment]
Ps. the apk is now available at the releases page.
