### ISSUE TITLE
Have reached maximum logins allowed

### ISSUE THREAD

**Issue by buylife** [leonardoxh/race-control-tv#18]
After installing your android app I can't log in to the official f1 tv app and get this message:

![7748EA25-7722-429E-A5B0-49B3BC0EABD6](https://user-images.githubusercontent.com/1515897/110993905-01ddbf80-8389-11eb-8df1-dce8d0d439d5.jpeg)

Please add a logout option 

Thank you so much

**Comment by leonardoxh** [comment]
Thank you for the issue, I am working in a button on the main screen to do add some "settings" and I will have the logout option right near it (soon as I find what api does this logout ofc)

**Comment by leonardoxh** [comment]
Hi again @buylife 

I have made a search, and **there is no logout api to clear that device association**, so there is no real way to solve your problem, only if your token expires, at the current app the token gets renewed every time automatically, so I still think that is valuable to add a logout option (soon) but it will not really solve your problem.

**Comment by schumi2004** [comment]
@buylife How many devices are associated to your account under the subscription section in account settings?
Although I have logged in multiple times on my laptop (browser) and Android TV's using F1TV Viewer for Android TV I only see 1 device registered and that's my mobile running the official F1 TV app.
Maybe remove a few devices that are associated like I did with my old cellphone.

**Comment by buylife** [comment]
Thank you guys for your support. I have no idea why on one device I still get the message but on the other device, everything is fine. I think I have to wait for the token to expire... I have read that the F1TV app should authorize each new device by clearing one of the previous devices...At the moment I have canceled my subscription and received a refund to speed up the token expiration. I'm going to renew my subscription soon.
