### ISSUE TITLE
Trying to log on with confirmed working credentials: "Credentials rejected by F1.com"

### ISSUE THREAD

**Issue by djpbessems** [leonardoxh/race-control-tv#19]
Hey there, was referred to this app by a fan.

Unfortunately, when I try to log on with my credentials (confirmed working on official F1TV app and website), I'm getting a toast message "Credentials rejected by F1.com".

My password only has alphanumeric characters, so it's unlikely to be caused by some encoding issues when using F1.com's REST api.
I tried looking through your code, but I'm seeing multiple files that deal with authentication, so not sure which file I should look in :)

**Comment by leonardoxh** [comment]
Are you using the latest Playstore version?

This was a bug on the original code due some missing headers

**Comment by djpbessems** [comment]
Yes, I downloaded the app from the play store twice. I'm using it on the new Chromecast w/ GoogleTV

**Comment by leonardoxh** [comment]
Interesting, I also have a Chromecast with Google TV, this happens because this method bellow on CredentialService, for some reason returns false. Could you print this exception message in this try catch and post it here so we can take a look ?

```kotlin
suspend fun checkAndSave(credentials: F1Credentials): Boolean =
        try {
            Log.d(TAG, credentials.toString())
            val token = f1.authenticate(credentials)
            f1CredentialsRepository.save(credentials)
            f1TokenRepository.save(token)
            true
        } catch (e: Exception) {
            Log.e(TAG, "Credentials rejected", e)
            false
        }
```

**Comment by djpbessems** [comment]
Ehm, can you point me in the right direction on how to do that? Do I need any special tools (is this relevant https://developers.google.com/cast/docs/debugging/remote_debugger)?

**Comment by leonardoxh** [comment]
ah, I tough you're an android developer :D 

If you switch your password does it work?

**Comment by djpbessems** [comment]
I changed my password (from a 32-character one to a 16-character one), but it didn't have any apparent effect.

**Comment by leonardoxh** [comment]
Hey @djpbessems I want to solve this issue.

Can you share with me a password that doesn't work ? (of course change not yours), because then I can change my password and check what is going one.

I have a strong indication that is a encoding issue

**Comment by djpbessems** [comment]
I'll create a temporary password later today, confirm that that one also does not work, then share it with you.
For what it's worth, my emailaddress has the following format (and could potentially be longer than supported - it wouldn't be the first faulty API I encounter with that issue :P): `formula1.com.<name>@<longdomain>.com`

**Comment by leonardoxh** [comment]
Yeah man this api is crap.

**Comment by leonardoxh** [comment]
Btw, @djpbessems 
Maybe it is better if you try to simulate the api call.

POST: https://api.formula1.com/v2/account/subscriber/authenticate/by-password
Body (json): 
{
    "Login": "YOUR_LOGIN",
    "Password": "YOUR_PASSWORD"
}

and check what is the response?

**Comment by djpbessems** [comment]
I tried the following:
(with `<key>` being the key taken from `app/src/main/java/fr/groggy/racecontrol/tv/f1/F1Client.kt` and `<mailaddress>` and `<password>` obviously my credentials)
```
Try {
    $InvokeWebRequestSplat = @{
        Uri = 'https://api.formula1.com/v2/account/subscriber/authenticate/by-password'
        Method = 'POST'
        Headers = @{'apiKey'='<key>';'User-Agent'="RaceControl f1viewer"}
        UseBasicParsing = $True
        Body = @{
                Login = '<mailaddress>'
                Password = '<password>'
            } | ConvertTo-Json
    }
    $Response = Invoke-WebRequest @InvokeWebRequestSplat
}
Catch [System.Net.WebException] {
    $StreamReader = [System.IO.StreamReader]::new($_.Exception.Response.GetResponseStream())
    $StreamReader.BaseStream.Position = 0
    $ErrResponse = $StreamReader.ReadToEnd()
    $StreamReader.Close()
}

If ($Response) {$Response | ConvertFrom-Json}
If ($ErrResponse) {$ErrResponse | ConvertFrom-Json}
```
The result was:
```
ContextId        : df846a09-54da-41dd-8942-a9b01a951f07
Code             : @{Severity=4; Value=118; DisplayName=InvalidProperty}
ExternalCode     : 
PropertyProblems : {@{Name=; Detail=}}
Extensions       : 
Type             : 
Title            : InvalidProperty
Status           : 422
Detail           : Invalid model state
Instance         : 
```

**Comment by leonardoxh** [comment]
This is one of the most weird thins I have seen.

It is basically a api error, and I there is nothing I can do on app side, I will google a bit to see if there is a work around or so to do but honestly no ideas

**Comment by leonardoxh** [comment]
I found this...

https://github.com/SoMuchForSubtlety/f1viewer/issues/60

Apparently there is no real solution :{

**Comment by djpbessems** [comment]
It's okay, I'll just have to suffer through more Olav Mol then... ;)
