### ISSUE TITLE
Support other shows?

### ISSUE THREAD

**Issue by schumi2004** [leonardoxh/race-control-tv#20]
I was curious if you're going to support other shows in the app like Tech Talk, F1 Highlights, interviews etc in the near future?

**Comment by leonardoxh** [comment]
Hi thanks for your message.

That is a possibility soon as I migrate to the 2.0 apis

**Comment by leonardoxh** [comment]
Hey @schumi2004 (nice name btw)

All these events are now on the app (I get them now with the 2.0 apis). I released it to 25% of users on play store

**Comment by schumi2004** [comment]
That's great unfortunately I'm not in those 25%, didn't find an update (yet) ;)
