### ISSUE TITLE
Playback control is difficult

### ISSUE THREAD

**Issue by j0bro** [leonardoxh/race-control-tv#30]
While playing a video:

- it's hard to see which UI element is highlighted (the transparent background is too subtle to make out)
- it's hard to make jumps in the playback position. The progress bar does not react to scroll input and the Rewind/FF buttons always skip the same (short) amount of time.

Suggestions:
- [ ] Make highlight background more visible (less transparent, or give it a bright color)
- [ ] Change the Rewind/FF buttons into skip 30s back/forward buttons
- [ ] Make the progress bar scrollable, let scroll speed increase while pressing left or right repeatedly

**Comment by leonardoxh** [comment]
Hi, I enabled the ability to seek to whatever position you want with the progress bar.

it is available at this PR: #31

**Comment by leonardoxh** [comment]
It will get some days until this gets released, but it is there
