### ISSUE TITLE
Sideload 2.0.0 APK: INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by whitenrock** [leonardoxh/race-control-tv#32]
When i try to sideload the 2.0.0 APK from [here](https://github.com/leonardoxh/race-control-tv/releases/tag/v2.0.0), i get the following error:

INSTALL_PARSE_FAILED_NO_CERTIFICATES

**Comment by leonardoxh** [comment]
I believe this has to do with the apk signature V2 (I did not added V1) can you share more details about your device like model and Android version, then I can re-generate the apk with both signatures

**Comment by leonardoxh** [comment]
Hi @whitenrock 

I just released v2.0.1 with a new APK that attempts to fix this issue:
https://github.com/leonardoxh/race-control-tv/releases/tag/v2.0.1

Please let me know if it works.

**Comment by whitenrock** [comment]
Hi @leonardoxh,

thank you for your quick response, now it works.
Thanks for the app, great work!

Best regards
