### ISSUE TITLE
Leonardo's race-control-tv working perfect of NVidia Shield set-top box

### ISSUE THREAD

**Issue by rafael2k** [leonardoxh/race-control-tv#39]
This is a non issue, but I'd like to thank Leonardo. Now race-control-tv is infinitelly better than official F1TV on an NVidia Shield Android TV set-top box. I can use nvidia remote without issue, in order to access the content.

Thanks to all original race-control-tv authors and Leonardo, especially. 

Obrigado!

**Comment by leonardoxh** [comment]
Valeu mano 👊🏾
