### ISSUE TITLE
Internacionalization

### ISSUE THREAD

**Issue by rafael2k** [leonardoxh/race-control-tv#40]
Hi Leonardo,
Do you have a plan to provide support for other languages?

In Brazil, many young F1 fans know English, but old school ones, like my father, does not. I could help with a Brazilian Portuguese (why not European Portuguese also) translation, if you decide to pursue this development path.

Cheers and go go go Perez!!
:P

Rafael

**Comment by rafael2k** [comment]
Just a small comment.
; )

**Comment by leonardoxh** [comment]
Então cara

I had already the idea to translate it, just did not had feeling for it yet :D 

But translations PR's are more than welcome for sure, I think it is important Portuguese, Spanish and Dutch, most of the content really comes from F1 TV api I think we only have 10 ~ 15 strings to translate

**Comment by rafael2k** [comment]
Oi Leonardo!

I agree that some translations will be good. But indeed, now using the software for more than a week, it is not hard to use it even for someone who does not know English.

Abraço!
