### ISSUE TITLE
Bug at Mi Box - Half season only

### ISSUE THREAD

**Issue by ahtramos** [leonardoxh/race-control-tv#41]
First of all, MUITO OBRIGADO! You and Groogy did what those geniuses at F1 TV should have done 3 years ago.

I have downloaded v2.0.0 to my MiBox 4K and, besides those small bugs, it worked great.

Now, with v2.0.2, it still works great, but the 2018 to 2020 seasons only shows the first half of the season. The 2nd half races are nowhere to be seen. For example, 2020 season stops at Tuscany GP, see pic below. The v2.0.0 showed all 2020 season. It would be great if you could see what happened (I tried everything before I came here: reinstalled, reset HW, cleared cache, restarted box, but no avail). I have F1 TV Access and I can watch all races at the official app.

![image](https://user-images.githubusercontent.com/81402443/112577867-fd2af980-8dd3-11eb-9073-cb88a102c38a.jpg)

Thanks in advance for your effort.

**Comment by leonardoxh** [comment]
Hi,

In terms of loading the seasons there is no changes from v2.0.0 to v2.0.2 I will investigate a bit, but I suspect that this is somehow an outage on F1 side (not rare to be honest), I think they are still developing very hard the API, but I see bellow of the Tuscan Grand Prix the styrian one... are you sure there is no more items bellow it ?

**Comment by leonardoxh** [comment]
Hi again I quickly looked at the APIs and there is something weird going on there

You only see 10 race weekends on the list because the api is only returning these 10 events, interesting enough if I remove this parameter from the api call `&filter_orderByFom=Y` it returns another 10 different events like the Turkish Grand Prix.

There is probably an underline change in the API that we need to adapt on the app.

Let's leave this issue open for now I will check in other repositories if there is some changes related to this already and attempt to patch it.

**Comment by leonardoxh** [comment]
HA!, Founded it here:

https://github.com/robvdpol/RaceControl/commit/64d49a6ce390e650ddb2ed7a1c881146391f0cae

It is a small change on F1 api, I will push a fix today

**Comment by leonardoxh** [comment]
Yes!

I published the update to the store now, it should be available in some hours

https://github.com/leonardoxh/race-control-tv/releases/tag/v2.0.3

**Comment by ahtramos** [comment]
Thank you very much again. Full seasons on display now. I thought at first it could be some temporary problem with the F1 app, but I was having this problem for a couple of days straight. All good today. Hoping that when (if?) they decide to do an Android TV version, it could work as good as yours. Will call for help again if I see something weird.

**Comment by leonardoxh** [comment]
I think when they release an app probably it will be much better with official support (or not) 😂😂😂😂
