### ISSUE TITLE
Season events order is not optimal

### ISSUE THREAD

**Issue by leonardoxh** [leonardoxh/race-control-tv#42]
Right now this is order somehow by the start date desc, but what happens is that this only works for the sessions, the season itself does not contain a date to order with, so when the season is in the middle for example it is order from the pre season to the most recent, should it be the other way?

**Comment by anton264** [comment]
I think it should always select the most recent event, I mostly use this app to watch live and I want to get to the live content fast.

**Comment by leonardoxh** [comment]
Yeah I have the same feeling. I think today is a good day to implement this should be straight forward
