### ISSUE TITLE
Retry backoff on playback

### ISSUE THREAD

**Issue by leonardoxh** [leonardoxh/race-control-tv#48]
Some times... Due F1 API issues, the playback crashes before it starts... Would be nice to retry sometimes

**Comment by andrew-dixon** [comment]
I've managed to get it working by clearing the cache and data, then logging in again, not sure if that helps at all, but thought I'd let you know.

**Comment by leonardoxh** [comment]
Interesting then it might be a database cache issue perhaps

**Comment by andrew-dixon** [comment]
@leonardoxh Thanks for the great work 👍

**Comment by leonardoxh** [comment]
@andrew-dixon did the last build help to solve the problema a bit ?

Usually during the week no body opens the app but when is race weekend there is lots of opening so we can solve the issue

**Comment by andrew-dixon** [comment]
@leonardoxh I've just tried the latest update and it all worked ok, as it did before after I cleared the cache and data. The new options in this version for selecting the quality and closed captions are great additions and both worked fine as well. Let's see how it goes in a couple of weeks with the Imola race.
