### ISSUE TITLE
Closed Captioning Possible?

### ISSUE THREAD

**Issue by gatesl** [leonardoxh/race-control-tv#50]
Does the feed support closed captioning?  Seems to be the only thing missing to bring the app to parity with the browser based experience.

**Comment by leonardoxh** [comment]
For sure :)

Just need to play around a bit

**Comment by leonardoxh** [comment]
I raised a PR with the closed caption support  I just need some other fixes but this will be bundled this week to production.

![IMG_20210329_184037.jpg](https://user-images.githubusercontent.com/1267788/112870318-5d64b880-90be-11eb-9c38-beed85b2a4ed.jpg)

**Comment by gatesl** [comment]
Great news!  We will test it out as soon as it's in production.  Thank you!
