### ISSUE TITLE
Spinning wheel after menu selections, buffering during playback

### ISSUE THREAD

**Issue by Jeremy7600** [leonardoxh/race-control-tv#59]
Opening the app results in a spinning wheel for 2 to 3 minutes (same happens when I clear cache/data and sign in again). Then I can choose a year. Once the year is chosen, another 2 or 3 minutes of spinning wheel on the screen. Then the sessions come up with no thumbnails. I select the replay of the Bahrain race and another 2 to 3 minute spinning wheel. Then the content plays for about 30 to 40 seconds and another spinning wheel. Content is unwatchable, even at 288p50, because it is buffering every 30 seconds.

**Comment by leonardoxh** [comment]
Hi, I released v2.0.6 right now that should be available on play store in some hours, can you try with the new version?

**Comment by Jeremy7600** [comment]
Still buffering during playback, about 3 or 4 times in the first 40 seconds of video. Still a spinning wheel after menus, as well. I tried both the Qualy and the Race replays of Bahrain 2021. I have no issues with other players, even casting F1 to this device. The device is a 2017 nVidia Shield.

**Comment by leonardoxh** [comment]
Well after choose the season there is multiple network requests going one so no surprises there.

If I just see the issue you described seems more like a network issue rather than a app issue, I know that many users have this Nvidia shield and do not experience these problems.

Can you share for sanity a speed test of your device here ? 

Also you mentioned that with replay of 21 race you did not have problems, can you also point a few races that u have the problem ?

**Comment by Jeremy7600** [comment]
I'm seeing about 40Mbps down and 15Mbps up through 2 different speed test apps. 

Everything has the problem. I haven't been able to watch anything on the app, it all buffers.

**Comment by leonardoxh** [comment]
Hmm, not being rude, but I have no idea how to help :)

Maybe switching networks or something like that because definitely doesn't seem like an app problem

**Comment by Jeremy7600** [comment]
Respectfully, I disagree that its a network issue or hardware issue. I just moved the Shield to my office, connected it via gigabit ethernet, tested the internet speed at 80Mbps (twice as fast as before) and the buffering is just as bad. I use Race Control on my desktop and have zero issues. I log in to Race Control and it takes 2 seconds to log in, not 90. I select which season I want and the menu options are there almost instantly, not 90 seconds later. I pull up a video and it plays within about 10 seconds, not 90 seconds later. The Race Control App shows a 3 minute cache being built within MPV (which means it will play for the next 3 minutes without any buffering). I'm not sure what is going wrong. Maybe you could consult the Race Control developer to see what he is doing? Can I provide you with a log? If both apps are having different behavior on the same network connection, the issue is **not the network**.

**Comment by leonardoxh** [comment]
Well the race control, has many more features than this app at moment... So it might be that the plugin that is used is better, maybe might be that they build something that makes the playback better, I agree.

The thing is that at moment I can't really say to you that this is going to be fixed soon, give an ETA or something, I believe that if we do something will be a deep fix/improvement I will keep this issue open and an eye for it, but I can't really guarantee when this is going to be addressed.

**Comment by leonardoxh** [comment]
I added support for DASH stream instead of HLS (you can switch via app settings) in v2.4.0 maybe this addresses this issue?
