### ISSUE TITLE
Add broadcasts coming up to session view

### ISSUE THREAD

**Issue by bashopman** [leonardoxh/race-control-tv#67]
The current session view shows past or current broadcasts like this:
![image](https://user-images.githubusercontent.com/7276252/117513690-8ff1b300-af92-11eb-8590-994ef6572d24.png)
From this UI it is not clear which and when next broadcasts can be expected. You'll have to check the website or use F1 TV app on your phone. 

It would be very nice if the session view also shows cards for broadcasts coming up during the grand prix weekend, like in this mock-up for the next training session:
![image](https://user-images.githubusercontent.com/7276252/117514249-b532f100-af93-11eb-8f8c-4c9f9d2c37d1.png)
In this mock-up, the future session card is raised. I think future session cards should not be raised, because they are really just placeholders for future broadcast and cannot be clicked on.

Looking at the Formula 1 website, I found that https://api.formula1.com/v1/event-tracker returns information about the race weekend, including the dates and times of each session;
```
{
  "seasonContext": {
    "timetables": [{
        "state": "upcoming",
        "session": "p3",
        "gmtOffset": "+02:00",
        "description": "Practice 3",
        "endTime": "2021-05-08T13:00:00",
        "startTime": "2021-05-08T12:00:00"
      }, {
        "state": "completed",
        "session": "p2",
        "gmtOffset": "+02:00",
        "description": "Practice 2",
        "endTime": "2021-05-07T16:00:00",
        "startTime": "2021-05-07T15:00:00"
      }, {
        "state": "upcoming",
        "session": "r",
        "gmtOffset": "+02:00",
        "description": "Race",
        "endTime": "2021-05-09T17:00:00",
        "startTime": "2021-05-09T15:00:00"
      }, {
        "state": "completed",
        "session": "p1",
        "gmtOffset": "+02:00",
        "description": "Practice 1",
        "endTime": "2021-05-07T12:30:00",
        "startTime": "2021-05-07T11:30:00"
      }, {
        "state": "upcoming",
        "session": "q",
        "gmtOffset": "+02:00",
        "description": "Qualifying",
        "endTime": "2021-05-08T16:00:00",
        "startTime": "2021-05-08T15:00:00"
      }
    ],
  },
}
```

**Comment by bashopman** [comment]
@leonardoxh What do you think about this concept and using this API? I couldn't find it, but do you know if the v2 API supports information like this?

**Comment by leonardoxh** [comment]
I like the idea, and in fact we had this when we had the API v1 implemented, but when I migrated to v2 api this was lost. I am not sure what is the endpoint that returns this information, we could look at other F1 apps to see if they support this.

I believe this is probably already present in the API's we use (since all those apis call have around 6k lines of response), and we could (I think not sure) archive it by changing some parameters (this api is so weird).

This response you pasted is good, but it misses some UI elements that we would have to work around like image and `contentId` but it is a possibility.

**Comment by bashopman** [comment]
Glad you like the idea!
I'll explore the v2 API some more to see if I can get the required data.

**Comment by bashopman** [comment]
@leonardoxh Implemented and merged.
