### ISSUE TITLE
app never goes into 1080p

### ISSUE THREAD

**Issue by thanatos1219** [leonardoxh/race-control-tv#76]
Hi! I know the homepage says the app knows how to switch between 720p and 1080p depending on the bandwidth, but whether I select 1080p myself or leave it on auto, it never goes to 1080p 

I know the bandwidth is enough for 1080p as it loads without issues on the F1tv website 

Would there be any way to force it to load the 1080p stream?

**Comment by leonardoxh** [comment]
Hi, I am not really sure why this happens in fact.

I released today a new update to google play that contains a way to change the stream type between DASH and HLS, maybe give a shot in this 2 stream types it might solve it.

If not, later this week I will probably launch something that will allow the app to use external players to play content such as VLC, that might also help a bit.
