### ISSUE TITLE
cant start stream since v2.2.0

### ISSUE THREAD

**Issue by rsstnc147** [leonardoxh/race-control-tv#83]
Unfortunately since the new Version i'm not able to chose the streams anymore. It doesnt highlight the footage and i can't access the streams. I headed back to v2.1.1 and it works like intended.

**Comment by ruppy99** [comment]
Having same issue here on fire stick

**Comment by douglasriper** [comment]
I also have this issue with 2.2.2 on Android TV 7.1.1

**Comment by leonardoxh** [comment]
Yeah, It will be fixed when I merge this -> https://github.com/leonardoxh/race-control-tv/pull/84

**Comment by leonardoxh** [comment]
Ps. The issue closed when I merged the PR but I made v2.2.1 available right now as the APK, the release on play store should be available later today, but let me know if it is all ok

**Comment by ruppy99** [comment]
Issue still seems to be present in 2.2.1

**Comment by leonardoxh** [comment]
Hi we have this issue now https://github.com/leonardoxh/race-control-tv/issues/85

I just posted a link to the Alpha program, so we can investigate it
