### ISSUE TITLE
Retain email address (and maybe password) on login failure

### ISSUE THREAD

**Issue by dseven** [leonardoxh/race-control-tv#95]
Getting connected with VPN can be .... a bit challenging at times. I'm often running into the "API bug", and have to make several attempts until I finally get in. The problem is that every time it fails, the email address that I login with gets erased (along with the password), and I have to enter them again, which is a royal pain with a remote control and on-screen "keyboard". I wonder if it would be possible to not erase the email address (at least - maybe password too?) on login failure?

**Comment by leonardoxh** [comment]
Hi, I think that is a possibility for sure... The only problem I see is that this is a potential security issue by leaving your password there exposed... But we could think in something
