### ISSUE TITLE
Feature. Change background based on the card selected 

### ISSUE THREAD

**Issue by CristianSarac** [leonardoxh/race-control-tv#96]
What is your opinion on a feature where the background will change based on the card selected ? 

It will look something like this (I hope the pictures are pretty clear, couldn't upload a video for now)
![device-2021-09-16-151433](https://user-images.githubusercontent.com/3420861/133619494-d04501b6-74eb-46f4-8730-3ca30997e215.png)
and this 

![device-2021-09-16-151347](https://user-images.githubusercontent.com/3420861/133619526-c296fc3b-80c7-432d-9328-3e397e2025b7.png)

There is also a nice fade transition when changing the card. 

I think it will give the app a  more immersive or personalised feel.For the  background images i used the same url that is for Thumbnails but changed the resolution so that the picture will not be cropped like in the thumbnails.

**Comment by leonardoxh** [comment]
Yeah I really like the idea.

What is the resolution you're planing to use ?  The current screen resolution I suppose or fixed ?

**Comment by CristianSarac** [comment]
Awesome 
Well for the images i used this "https://ott.formula1.com/image-resizer/image/%s?w=1920&h=1080&o=L&q=HI" so that i get the highest resolution and later on when i load it the background i use Glide.
First i get the screen resolution , something like this `requireActivity().windowManager.defaultDisplay.getMetrics(metrics)` and then with glide i load in a custom drawable  `.into<CustomTarget<Drawable>>(object : CustomTarget<Drawable>(metrics.widthPixels, metrics.heightPixels) 
`
I have the initial code in a local branch , however i need to do some cleanup and cover some more cases and then i can make a PR .

**Comment by leonardoxh** [comment]
Implemented, but I am keeping this issue alive as it needs more work for the archive browse.
